# Generated by Django 2.2 on 2019-04-06 09:16

from django.db import migrations
import names
import random

def create_random_users(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model('random_user', 'Person')

    for i in range(0, 200):
        person = Person.objects.create()
        gender = 'male'
        if i % 2 == 0:
            gender = 'female'

        person.first_name = names.get_first_name(gender=gender)
        person.last_name = names.get_last_name()
        person.favorite_number = str(random.randint(1,1000))

        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('random_user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_random_users),
    ]
